service: tienda-backend

frameworkVersion: "4"
console: false

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 25
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

# 🚨 ACTUALIZAMOS EL EMPAQUETADO PARA INCLUIR LAS LIBRERÍAS DE PODMAN 🚨
package:
  individually: true
  exclude:
    - venv/**
    - .venv/**
    - .git/**
    - .serverless/**
    - .requirements/**
    - README.md

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: "{proxy+}"
          method: ANY
          cors: true
